version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group dependencies to reduce PR noise
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"
      trading-dependencies:
        patterns:
          - "yfinance"
          - "pandas"
          - "numpy"
    # Automatically approve and merge security updates
    reviewers:
      - "Y0nyx"
    assignees:
      - "Y0nyx"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"